services:
  postgres:
    image: postgres:16
    container_name: postgres_gestion_usuarios_victimas
    environment:
      POSTGRES_DB: db_gestion_usuarios_victimas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gestion72
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_gestion_usuarios_victimas"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: